apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.14.1  # latest stable version as of Oct 2025
    helm:
      releaseName: nginx-example-2
      values: |
        service:
          type: ClusterIP
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-example-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
