apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: kagent-crds
    repoURL: ghcr.io/kagent-dev/kagent/helm
    targetRevision: 0.7.4  # Update to desired version
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
