apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/agentadmin/agentic-k8s-charts.git
    targetRevision: main
    path: charts/gitea
    helm:
      valueFiles:
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: gitea-shared-storage
      namespace: gitea
      jsonPointers:
        - /metadata/annotations
        - /spec/volumeName
        - /spec/storageClassName
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
