server:
  service:
    type: NodePort
    ports:
      http: 80
      https: 443
    nodePortHttp: 30480
    nodePortHttps: 31443
  ingress:
    enabled: false
configs:
  params:
    server.insecure: "true"
  cm: {}

repoServer:
  service:
    type: ClusterIP

applicationSet:
  enabled: true
notifications:
  enabled: true
