# Default values for nginx-example.
# Tweak these to customize the deployment.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Leave blank to use the chart appVersion
  tag: ""

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30800

podLabels: {}

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http
