apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefox.fullname" . }}
  labels:
    {{- include "firefox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "firefox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "firefox.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: firefox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if not (hasKey .Values.env "FF_OPEN_URL") }}
            - name: FF_OPEN_URL
              value: {{ printf "http://127.0.0.1:%d/" (int .Values.dashboard.port) | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: vnc
              containerPort: 5900
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: firefox-dashboard
          image: "{{ .Values.dashboard.image.repository }}:{{ .Values.dashboard.image.tag }}"
          imagePullPolicy: {{ .Values.dashboard.image.pullPolicy }}
          ports:
            - name: dashboard
              containerPort: {{ .Values.dashboard.port }}
              protocol: TCP
          volumeMounts:
            - name: dashboard
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "firefox.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: dashboard
          configMap:
            name: {{ include "firefox.fullname" . }}-dashboard
